const fs=require('fs'),assert=require('node:assert/strict'),ts=require('typescript'),Module=require('module');
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText,f);
let user={id:'customer'},calls=[],rows={id:'req_test',user_id:'customer',dish_name:'Pilau',status:'PENDING'},rpcError=null,channels=[];
const supabase={auth:{getUser:async()=>({data:{user},error:null})},rpc:async(name,args)=>{calls.push({name,args});return {data:{id:'req_test'},error:rpcError};},from(table){const b={select(){return b},eq(){return b},insert(row){calls.push({insert:table,row});rows=row;return b},single:async()=>({data:rows,error:null}),maybeSingle:async()=>({data:rows,error:null})};return b},channel(name){const ch={name,on(_event,config,callback){ch.config=config;ch.callback=callback;return ch},subscribe(){return ch},unsubscribe(){ch.closed=true}};channels.push(ch);return ch}};
const load=Module._load;Module._load=function(id,parent,main){if(id==='../lib/supabase'||id==='./supabase')return {supabase,isSupabaseConfigured:()=>true};return load.apply(this,arguments)};
const {CustomMealRepository}=require('../repositories/customMeals.repository.ts');
const {ApplicationRepository}=require('../repositories/applications.repository.ts');
const {RealtimeServiceImpl}=require('../services/RealtimeService.ts');
let passed=0;async function check(name,fn){await fn();passed++;console.log('PASS',name)}
const valid={dishName:'Pilau',servingsCount:'2',budgetTzs:15000,customerArea:'Kijitonyama',desiredAt:new Date(Date.now()+6*3600000).toISOString(),exactDeliveryAddress:'Private address',exactDeliveryPhone:'255700000000',allergens:['nuts'],dietaryTags:['vegetarian']};
(async()=>{
await check('Customer submission uses matching RPC and preserves request fields',async()=>{const saved=await CustomMealRepository.createRequest(valid);assert.equal(saved.id,'req_test');assert.equal(calls[0].name,'create_structured_custom_meal_request');assert.equal(calls[0].args.p_exact_delivery_address,valid.exactDeliveryAddress);assert.equal(calls[0].args.p_exact_delivery_phone,valid.exactDeliveryPhone);assert.deepEqual(calls[0].args.p_allergens,['nuts']);assert.equal(calls.some(c=>c.insert),false);});
await check('Invalid budget, servings, area and timing are rejected before submission',async()=>{calls=[];for(const change of [{budgetTzs:4000},{servingsCount:'2.5'},{customerArea:''},{desiredAt:new Date().toISOString()}])await assert.rejects(()=>CustomMealRepository.createRequest({...valid,...change}));assert.equal(calls.length,0)});
await check('Backend failures are exposed; saved-but-unreadable request prevents blind retry',async()=>{rpcError={message:'permission denied'};await assert.rejects(()=>CustomMealRepository.createRequest(valid),/permission denied/);rpcError=null;rows=null;await assert.rejects(()=>CustomMealRepository.createRequest(valid),/Refresh your requests/)});
const app={businessName:'Kitchen',ownerName:'Owner',ownerPhone:'255700000000',cuisineType:'Swahili',address:'Address',neighborhood:'Area'};
await check('Restaurant submission requires a session and prevents identity substitution',async()=>{calls=[];user=null;await assert.rejects(()=>ApplicationRepository.submit(app),/sign in/);user={id:'owner'};await assert.rejects(()=>ApplicationRepository.submit({...app,applicantUserId:'someone-else'}),/identity/);assert.equal(calls.length,0);await ApplicationRepository.submit(app);assert.equal(calls[0].row.applicant_user_id,'owner');assert.equal(calls[0].row.status,'PENDING')});
await check('Realtime watches real invitation and order columns, including reconnect',async()=>{const rt=new RealtimeServiceImpl();let notified=0;rt.subscribeToCustomMeals('restaurant',()=>notified++);rt.subscribeToCustomerOrders('customer',()=>{});rt.subscribe('admin:applications',()=>{}, {table:'restaurant_applications'});assert(channels.some(c=>c.config?.table==='custom_meal_invitations'&&c.config.filter==='restaurant_id=eq.restaurant'));assert(channels.some(c=>c.config?.table==='orders'&&c.config.filter==='user_id=eq.customer'));const ch=channels.find(c=>c.config?.table==='custom_meal_invitations');ch.callback({table:'custom_meal_invitations',eventType:'INSERT',new:{id:'inv'}});assert.equal(notified,1);channels=[];rt.reconnect();assert(channels.some(c=>c.config?.table==='restaurant_applications'));assert(channels.some(c=>c.config?.table==='custom_meal_invitations'));rt.clearAll();assert(channels.every(c=>c.closed));});
console.log(`WORKFLOW CONTRACT: ${passed} groups passed. Supabase transport mocked; hosted SQL integration is a separate check.`);
})().catch(e=>{console.error(e);process.exitCode=1});
